input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    rename => {
      "trace_id" => "[trace][id]"
      "spanId"  => "[span][id]"
      "service" => "[service][name]"
      "level"   => "[log][level]"
      "logger_name" => "[log][logger]"
      "thread_name" => "[process][thread][name]"
    }

    remove_field => [
      "@version",
      "[event][original]",
      "[container][labels]",
      "[agent][ephemeral_id]",
      "[agent][ephemeral_id]",
      "[agent][id]",
      "[ecs][version]"
    ]

    add_field => {
      "event.dataset" => "credit-system.logs"
      "event.module"  => "credit-system"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "credit-system-logs-%{+YYYY.MM.dd}"
  }
}