global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: calculator-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'calculator-api:8092' ]
        labels:
          application: 'calculator-api'
          environment: 'production'
  - job_name: deal-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'deal-api:8093' ]
        labels:
          application: 'deal-api'
          environment: 'production'

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]
    basic_auth:
      username: admin
      password: admin
    scheme: http
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'elasticsearch'
    static_configs:
      - targets: [ 'elasticsearch-exporter:9114' ]
        labels:
          service: 'elasticsearch'
          stack: 'elk'