server:
  port: 8092

spring:
  application:
    name: calculator-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
  endpoint:
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms,100ms,200ms,500ms,1s,2s
  info:
    env:
      enabled: true
    git:
      mode: full

credit:
  base-rate: ${BASE_RATE:15.0}
  insurance-cost: ${INSURANCE_COST:100000}
  insurance-rate-discount: ${INSURANCE_RATE_DISCOUNT:3.0}
  salary-rate-discount: ${SALARY_RATE_DISCOUNT:1.0}
  min-amount: ${MIN_AMOUNT:20000}
  min-term: ${MIN_TERM:6}
  min-age: ${MIN_AGE:18}

otel:
  exporter:
    otlp:
      endpoint: ${OTLP_EXPORTER_ENDPOINT:http://localhost:4318}
      protocol: http/protobuf
  logs:
    exporter: none
  metrics:
    exporter: none
logging:
  config: "classpath:logback.xml"